const FETCHED_PARKS = "FETCHED_PARKS"
const LOADING_PARKS = "LOADING_PARKS"
const FETCHED_IMAGES = "FETCHED_IMAGES"
const CHANGING_SEARCH_TEXT = "CHANGING_SEARCH_TEXT"
const FILTER_STATE = "FILTER_STATE"

export {FETCHED_PARKS, LOADING_PARKS, FETCHED_IMAGES, CHANGING_SEARCH_TEXT, FILTER_STATE}